//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WESPLITEntities : DbContext
    {
        public WESPLITEntities()
            : base("name=WESPLITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COST> COSTs { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<TRIP> TRIPs { get; set; }
        public virtual DbSet<TRIP_COSTS> TRIP_COSTS { get; set; }
        public virtual DbSet<TRIP_IMAGES> TRIP_IMAGES { get; set; }
        public virtual DbSet<TRIP_LOCATIONS> TRIP_LOCATIONS { get; set; }
        public virtual DbSet<TRIP_MEMBERS> TRIP_MEMBERS { get; set; }
    }
}
