//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIP_COSTS
    {
        public int COST_ID { get; set; }
        public int TRIP_ID { get; set; }
        public Nullable<double> AMOUNT { get; set; }
    
        public virtual COST COST { get; set; }
        public virtual TRIP TRIP { get; set; }
    }
}
