//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRIP()
        {
            this.TRIP_COSTS = new HashSet<TRIP_COSTS>();
            this.TRIP_LOCATIONS = new HashSet<TRIP_LOCATIONS>();
            this.TRIP_MEMBERS = new HashSet<TRIP_MEMBERS>();
            this.TRIP_IMAGES = new HashSet<TRIP_IMAGES>();
        }
    
        public int TRIP_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string TITTLE { get; set; }
        public string THUMNAIL { get; set; }
        public double TOTALCOSTS { get; set; }
        public Nullable<System.DateTime> TOGODATE { get; set; }
        public Nullable<System.DateTime> RETURNDATE { get; set; }
        public Nullable<bool> ISDONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIP_COSTS> TRIP_COSTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIP_LOCATIONS> TRIP_LOCATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIP_MEMBERS> TRIP_MEMBERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIP_IMAGES> TRIP_IMAGES { get; set; }
    }
}
