//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIP_MEMBERS
    {
        public int TRIP_ID { get; set; }
        public int MEMBER_ID { get; set; }
        public double AMOUNT_PAID { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
        public virtual TRIP TRIP { get; set; }
    }
}
